Gemini/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Gemini.Libraries.Components;
using Gemini.Libraries.Components.ThemeEngine;
using Gemini.Libraries.Components.ThemeEngine.PageEngine.Enums;
using Gemini.Libraries.Components.ThemeEngine.PageEngine.PostViewModels;
using Gemini.Libraries.Components.Toast;
using Gemini.Libraries.Models;
using Gemini.Libraries.ViewModels.Pages;
using Gemini.Models;
using Gemini.Themes;
using Gemini.Themes.Default.ViewModel.Pages;
using Gemini.ViewModels.Pages;
using Microsoft.AspNet.Identity;
using PagedList;

namespace Gemini.Controllers
{
    /// <summary>
    /// Since: Rev ?a
    /// Current: Rev 4
    /// </summary>
    [Authorize]
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        private readonly ThemeRegistrar _themeRegistrar = new ThemeRegistrar();

        // GET: Pages
        public ViewResult Index(int? page)
        {
            int pageIndex = (page ?? 1) - 1;
            int pageSize = 10;
            int skip = (pageIndex == 0) ? 0 : pageIndex * pageSize;

            List<Posts> pages = _context.Posts
                .Where(x => x.PostType == PostTypes.Page)
                .OrderBy(x => x.PostId)
                .Skip(skip)
                .Take(pageSize)
                .ToList();

            List<PageViewModel> pageVMs = pages.Select(pageVm => new PageViewModel()
            {
                Id = pageVm.PostId,
                Title = pageVm.Title,
                Slug = pageVm.Slug,
                Status = pageVm.PostStatus,
                DateCreated = pageVm.DateCreated,
                DateUpdated = pageVm.DateUpdated
            }).ToList();

            PageListViewModel vm = new PageListViewModel
            {
                Pages =
                    new StaticPagedList<PageViewModel>(pageVMs, pageIndex + 1, pageSize,
                        _context.Posts.Count(x => x.PostType == PostTypes.Page))
            };
            return View(vm);
        }

        public ViewResult Create()
        {
            // retrieve view model with all of its meta from theme registrar
            return View(_themeRegistrar.GetPageViewModel());
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult ProcessNew(BasePageViewModel form)
        {
            if (!ModelState.IsValid)
                return View("Create", form);

            Posts post = new Posts()
            {
                Title = form.Title,
                Slug = UrlSlugger.Slugify(form.Title),
                Content = form.Content,
                UserId = HttpContext.User.Identity.GetUserId(),
                PostType = form.Type,
                PostStatus = form.Status,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now,
                Visibility = form.Visibility
            };
            _context.Posts.Add(post);

            foreach (BasePostMetaViewModel formMeta in form.Meta)
            {
                var themeName = _themeRegistrar.CurrentServiceProvider().ThemeName;
                _context.PostMeta.Add(new PostMeta()
                {
                    Post = post,
                    DateCreated = DateTime.Now,
                    Theme = themeName,
                    Meta = formMeta.Meta,
                    Value = formMeta.Value
                });
            }
            _context.SaveChanges();

            return RedirectToAction("View", new { id = post.PostId });
        }

        public ActionResult View(int id, bool? updated)
        {
            Posts model = _context.Posts.SingleOrDefault(post => post.PostId == id);

            if (model == null)
                return RedirectToAction("Index");

            string themeName = _themeRegistrar.CurrentServiceProvider().ThemeName;
            List<PostMeta> metaCol =
                _context.PostMeta
                .Where(x => x.PostId == id && x.Theme == themeName)
                    .ToList();

            BasePageViewModel vm = _themeRegistrar.GetEditPageViewModel();
            vm.Id = model.PostId;
            vm.UserId = model.UserId;
            vm.Title = model.Title;
            vm.Slug = model.Slug;
            vm.Content = model.Content;
            vm.Type = model.PostType;
            vm.Status = model.PostStatus;
            vm.Visibility = model.Visibility;
            vm.DateUpdated = model.DateUpdated;
            vm.Revisions = _context.Posts
                .Include(x => x.User)
                .Where(x => x.ParentId == model.PostId && x.PostType == PostTypes.Revision)
                .OrderByDescending(x => x.DateCreated)
                .Select(rev => new RevisionViewModel()
                {
                    Id = rev.PostId,
                    ParentId = (int)rev.ParentId,
                    UserId = rev.UserId,
                    User = rev.User,
                    DateCreated = rev.DateCreated
                })
                .ToList();

            if (metaCol.Any())
            {
                foreach (PostMeta modelMeta in metaCol)
                {
                    var overrideMeta = vm.Meta.SingleOrDefault(x => x.Meta == modelMeta.Meta);
                    if (overrideMeta == null)
                        continue;

                    overrideMeta.Value = modelMeta.Value;
                }
            }

            vm.DateCreated = model.DateCreated;

            if (updated != null && (bool) updated)
            {
                vm.Notify.Show = true;
                vm.Notify.Type = Notify.TypeInfo;
                vm.Notify.Title = "Updated!";
                vm.Notify.Message = "Page updated.";
            }

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Update(BasePageViewModel form)
        {
            Posts model = _context.Posts.Include(p => p.Meta).SingleOrDefault(p => p.PostId == form.Id);

            if (model == null)
                return RedirectToActionPermanent("Index");

            // only create revision if content does not match.
            if (model.Content != form.Content)
                CreateRevision(model.PostId, model.Title, model.Content);

            model.Slug = model.Title == form.Title ? model.Slug : UrlSlugger.Slugify(form.Title, model.PostId);
            model.Title = form.Title;
            model.Content = form.Content;
            model.PostStatus = form.Status;
            model.Visibility = form.Visibility;
            model.DateUpdated = DateTime.Now;

            string activeTheme = EngineState.Instance.ActiveTheme;
            foreach (BasePostMetaViewModel formMeta in form.Meta.ToList())
            {
                PostMeta dbMeta = model.Meta.SingleOrDefault(x => x.Meta == formMeta.Meta);
                if (dbMeta == null)
                {
                    PostMeta newMeta = new PostMeta()
                    {
                        Post = model,
                        Meta = formMeta.Meta,
                        Value = formMeta.Value,
                        Theme = activeTheme,
                        DateCreated = DateTime.Now,
                        DateUpdated = DateTime.Now
                    };
                    _context.PostMeta.Add(newMeta);
                }
                else
                {
                    dbMeta.Value = formMeta.Value;
                    dbMeta.DateUpdated = DateTime.Now;
                }
            }

            _context.SaveChanges();
            return RedirectToActionPermanent("View", new { id = form.Id, updated = true });
        }

        [Route("pages/revision/{postId:int}/{revisionId:int}")]
        public ActionResult Revision(int postId, int revisionId)
        {
            ViewRevisionViewModel post = _context.Posts
                .Join(
                    _context.Posts,
                    parent => parent.PostId,
                    child => child.ParentId,
                    (posts, child) => new ViewRevisionViewModel()
                    {
                        Id = posts.PostId,
                        RevisionId = child.PostId,
                        Content = posts.Content,
                        RevisionContent = child.Content,
                        Title = posts.Title,
                        RevisionTitle = child.Title
                    })
                    .SingleOrDefault(x => x.Id == postId && x.RevisionId == revisionId);

            if (post == null)
                return RedirectToAction("Index");

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult RestoreRevision(ViewRevisionViewModel form)
        {
            Posts post = _context.Posts
                .SingleOrDefault(p => p.PostId == form.Id);
            Posts revision = _context.Posts
            .SingleOrDefault(rev => rev.PostId == form.RevisionId && rev.PostType == PostTypes.Revision);

            if (post == null || revision == null)
                return RedirectToAction("Index");

            CreateRevision(post.PostId, post.Title, post.Content);
            post.Title = revision.Title;
            post.Slug = UrlSlugger.Slugify(post.Title, post.PostId);
            post.Content = revision.Content;
            post.DateUpdated = DateTime.Now;
            _context.SaveChanges();

            return RedirectToAction("View", new { id = post.PostId });
        }

        private void CreateRevision(int id, string title, string content)
        {
            Posts rev = new Posts()
            {
                UserId = HttpContext.User.Identity.GetUserId(),
                Title = title,
                Content = content,
                PostType = PostTypes.Revision,

Gemini/Controllers/PostsController.cs
using System.Web.Mvc;

namespace Gemini.Controllers
{
    /// <summary>
    /// Since: Rev ?a
    /// Current: Rev 4
    /// </summary>
    public class PostsController : Controller
    {
        // GET: Posts
        public ActionResult Index()
        {
            return View();
        }

        public ViewResult Create()
        {
            return View();
        }
    }
}

Gemini/Controllers/SettingsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Gemini.Libraries.Components.Settings;
using Gemini.ViewModels.Settings;

namespace Gemini.Controllers
{
    /// <summary>
    /// Since: Rev 5a
    /// Current: Rev 4
    /// </summary>
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly SettingsComponent _settingsComponent = new SettingsComponent();

        public ViewResult General()
        {
            GeneralSettingsFormData vm = new GeneralSettingsFormData()
            {
                FormAction = Url.Action("UpdateGeneral"),
                SiteTitle = _settingsComponent.Get(Entities.Global, Attributes.SiteTitle),
                SiteTagline = _settingsComponent.Get(Entities.Global, Attributes.SiteTagline)
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateGeneral(GeneralSettingsForm form)
        {
            if (ModelState.IsValid)
            {
                _settingsComponent.Set(Entities.Global, Attributes.SiteTitle, form.SiteTitle, true);
                _settingsComponent.Set(Entities.Global, Attributes.SiteTagline, form.SiteTagline, true);

                return Json(new { Errors = false });
            }

            List<string> errors = new List<string>();
            foreach (KeyValuePair<string, ModelState> item in ModelState)
            {
                errors.AddRange(item.Value.Errors.Select(accessedErr => accessedErr.ErrorMessage));
            }

            return Json(new { Errors = true, Messages = errors });
        }
    }
}

Gemini/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Gemini.DataTransferObjects.Tag;
using Gemini.Libraries.Components;
using Gemini.Libraries.Components.ThemeEngine.PageEngine.Enums;
using Gemini.Libraries.Models;
using Gemini.Models;
using Gemini.ViewModels.Tags;

namespace Gemini.Controllers
{
    /// <summary>
    /// Since: Rev ?a
    /// Current: Rev 4
    /// </summary>
    [Authorize]
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Tags
        public ViewResult Index()
        {
            return View(new TagListViewModel()
            {
                CreateUrl = Url.Action("Create"),
                DataUrl = Url.Action("TagData"),
                UpdateUrl = Url.Action("Update"),
                DeleteUrl = Url.Action("Delete")
            });
        }
    
        [OutputCache(Duration = 0)]
        public JsonResult TagData()
        {
            return Json(_context.PostGroup
                .Include(x => x.Posts)
                .Where(x => x.Type == PostGroupType.Tag)
                .OrderBy(x => x.Name)
                .Select(post => new TagItemDto()
                {
                    Id =  post.Id,
                    Description = post.Description,
                    Name = post.Name,
                    PostCount = post.Posts.Count,
                    Slug = post.Slug
                }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(TagViewModel form)
        {
            bool isUnique =
                _context.PostGroup.FirstOrDefault(x => x.Type == PostGroupType.Tag && x.Name == form.Name) == null;

            if (!ModelState.IsValid || !isUnique)
            {
                List<string> errors = new List<string>();
                foreach (KeyValuePair<string, ModelState> item in ModelState)
                {
                    errors.AddRange(item.Value.Errors.Select(accessedErr => accessedErr.ErrorMessage));
                }

                if (!isUnique)
                    errors.Add("Tag should be unique.");

                return Json(new
                {
                    Errors = true,
                    Messages = errors
                });
            }

            _context.PostGroup.Add(new PostGroup()
            {
                Name = form.Name,
                Description = form.Description,
                Slug = form.Slug,
                Type = PostGroupType.Tag,
                DateCreated = DateTime.Now
            });
            _context.SaveChanges();

            return Json(new
            {
                Errors = false
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Update(TagViewModel form)
        {
            bool isUniqueToForm =
                _context.PostGroup.FirstOrDefault(
                    x => x.Type == PostGroupType.Tag && x.Name == form.Name && x.Id != form.Id) == null;

            if (ModelState.IsValid && isUniqueToForm)
            {
                PostGroup model = _context.PostGroup.FirstOrDefault(x => x.Id == form.Id);
                model.Name = form.Name;
                model.Slug = UrlSlugger.ToUrlSlug(form.Name);
                model.Description = form.Description;

                _context.SaveChanges();
                return Json(new { Errors = false });
            }

            List<string> errors = new List<string>();
            foreach (KeyValuePair<string, ModelState> item in ModelState)
            {
                var errs = item.Value.Errors;
                errors.AddRange(errs.Select(accessedErr => accessedErr.ErrorMessage));
            }

            if (!isUniqueToForm)
                errors.Add("Tag should be unique.");

            return Json(new { ErrCol = errors, Errors = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(TagListDeleteViewModel tagList)
        {
            try
            {
                int[] itemIds = tagList.Items.Select(x => x.Id).ToArray();
                List<PostGroup> items =
                    _context.PostGroup.Where(x => x.Type == PostGroupType.Tag && itemIds.Contains(x.Id)).ToList();
                _context.PostGroup.RemoveRange(items);
                _context.SaveChanges();

                return Json(new {Errors = false});
            }
            catch (Exception e)
            {
                return Json(new { Errors = true, Message = "An error has occurred."});
            }
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Gemini/Views/Shared/AdminHeader.cshtml
@using Gemini.Libraries.Components
@using Gemini.Models
@{
    bool auth = Request.IsAuthenticated;
}
<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Index", "Home")" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Gmn</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Gemini</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        @if (@auth)
        {
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs">@Auth.Instance.ShowName()</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="@Url.Action("Index", "Manage")" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="@Url.Action("LogOut", "Account")" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        }
    </nav>
</header>

Gemini/Views/Shared/AdminSidebar.cshtml
@{
    bool auth = Request.IsAuthenticated;
}
<aside class="main-sidebar">
    <section class="sidebar">
        @if (@auth)
        {
            <ul class="sidebar-menu">
                <li class="header">MAIN NAVIGATION</li>
                <li id="index">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-tachometer"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li id="pages" class="treeview">
                    <a href="#">
                        <i class="fa fa-file"></i>
                        <span>Pages</span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("Index", "Pages")">
                                <span>All Pages</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Pages")">
                                <span>Add New</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li id="posts" class="treeview">
                    <a href="#">
                        <i class="fa fa-thumb-tack"></i>
                        <span>Posts</span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("Index", "Posts")">
                                <span>All Posts</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Posts")">
                                <span>Add New</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Categories")">
                                <span>Categories</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Tags")">
                                <i></i>
                                <span>Tags</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li id="appearance" class="treeview">
                    <a href="@Url.Action("Index", "Appearance")">
                        <i class="fa fa-paint-brush"></i>
                        <span>Appearance</span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("Index", "Appearance")">
                                <span>Themes</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li id="settings" class="treeview">
                    <a href="#">
                        <i class="fa fa-cogs"></i>
                        <span>Settings</span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="@Url.Action("General", "Settings")">
                                <span>General</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Manage Logo</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span>About Gemini</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        }
        else
        {
            <ul class="sidebar-menu">
                <li class="treeview">
                    <a href="@Url.Action("Login", "Account")">
                        <i class="fa fa-circle-o"></i>
                        <span>Login</span>
                    </a>
                </li>
            </ul>
        }
    </section>
    <!-- /.sidebar -->
</aside>

Gemini/Views/Shared/_Layout.cshtml
@{
    bool auth = Request.IsAuthenticated;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Gemini</title>
    @Styles.Render("~/bundles/css")
</head>
<body class="sidebar-mini skin-blue">
    <div class="wrapper">
        @Html.Partial("AdminHeader")
        @Html.Partial("AdminSidebar")
        <div class="content-wrapper">
            @*        <section class="content-header">*@
            @*            <h1>*@
            @*                Dashboard<small>Control panel</small>*@
            @*            </h1>*@
            @*            <ol class="breadcrumb"></ol>*@
            @*        </section>*@
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right">
                @*            <b>Revision</b> 160*@
            </div>
            <p>&copy; @DateTime.Now.Year - Gemini</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/app/gemini.bundle.js")
    @RenderSection("Scripts", false)
</body>
</html>